SaffronCity_Dojo_Text_MasterKoichiIntro::
    .string "Grunt!\p"
    .string "I am the KARATE MASTER!\n"
    .string "I am the LEADER here!\p"
    .string "You wish to challenge us?\n"
    .string "Expect no mercy!\p"
    .string "Fwaaa!$"

SaffronCity_Dojo_Text_MasterKoichiDefeat::
    .string "Hwa!\n"
    .string "Arrgh! Beaten!$"

SaffronCity_Dojo_Text_ChoosePrizedFightingMon::
    .string "Indeed, I have lost!\p"
    .string "But, I beseech you, do not take\n"
    .string "our emblem as your trophy!\p"
    .string "In return, I will give you a prized\n"
    .string "FIGHTING POKéMON!\p"
    .string "Choose whichever one you like!$"

SaffronCity_Dojo_Text_StayAndTrainWithUs::
    .string "Grunt!\n"
    .string "Stay and train at karate with us!$"

SaffronCity_Dojo_Text_MikeIntro::
    .string "Hoargh!\n"
    .string "Take your shoes off!$"

SaffronCity_Dojo_Text_MikeDefeat::
    .string "I give up!$"

SaffronCity_Dojo_Text_MikePostBattle::
    .string "You wait 'til you see our MASTER!\n"
    .string "I'm a small fry compared to him!$"

SaffronCity_Dojo_Text_HidekiIntro::
    .string "I hear you're good!\n"
    .string "Show me!$"

SaffronCity_Dojo_Text_HidekiDefeat::
    .string "Judge!\n"
    .string "One point!$"

SaffronCity_Dojo_Text_HidekiPostBattle::
    .string "Our MASTER is a pro fighter.\n"
    .string "Be prepared to lose!$"

SaffronCity_Dojo_Text_AaronIntro::
    .string "Hiyah!\n"
    .string "I have no fear for anything tough!\p"
    .string "I shatter boulders for training\n"
    .string "every day!$"

SaffronCity_Dojo_Text_AaronDefeat::
    .string "Yow!\n"
    .string "Stubbed fingers!$"

SaffronCity_Dojo_Text_AaronPostBattle::
    .string "The only thing that frightens us is\n"
    .string "psychic power!$"

SaffronCity_Dojo_Text_HitoshiIntro::
    .string "Hwaah!\p"
    .string "You're trespassing in our\n"
    .string "FIGHTING DOJO!$"

SaffronCity_Dojo_Text_HitoshiDefeat::
    .string "Oof!\n"
    .string "I give up!$"

SaffronCity_Dojo_Text_HitoshiPostBattle::
    .string "The prime fighters across the land\n"
    .string "train here.$"

SaffronCity_Dojo_Text_YouWantHitmonlee::
    .string "You want the hard-hitting\n"
    .string "MEDICHAM?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster::
    .string "{PLAYER} received the {STR_VAR_1}\n"
    .string "from the KARATE MASTER.$"

SaffronCity_Dojo_Text_YouWantHitmonchan::
    .string "You want the big, bulky\n"
    .string "HARIYAMA?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster2::
    .string "{PLAYER}は　カラテ　だいおう　から\n"
    .string "{STR_VAR_1}を　もらった！$"

SaffronCity_Dojo_Text_BetterNotGetGreedy::
    .string "Better not get greedy…$"

SaffronCity_Dojo_Text_EnemiesOnEverySide::
    .string "Enemies on every side!$"

SaffronCity_Dojo_Text_GoesAroundComesAround::
    .string "What goes around comes around.$"

SaffronCity_Dojo_Text_FightingDojo::
    .string "FIGHTING DOJO$"

SaffronCity_Dojo_Text_TakeThisTM52::
    .string "Your strength is truly\n"
    .string "prodigious!\p"
    .string "Here, you have earned this.$"

SaffronCity_Dojo_Text_ReceivedTM52FromKoichi::
    .string "{PLAYER} received TM52\n"
    .string "from KOICHI.$"

SaffronCity_Dojo_Text_ExplainTM52::
    .string "TM52 contains FOCUS BLAST.\p"
    .string "It is a rare Special FIGHTING\n"
    .string "move that may lower SpDef.\p"
    .string "It's very powerful, but can\n"
    .string "miss occasionally.$"

SaffronCity_Dojo_Text_ShouldMakeRoomForThis::
    .string "You should make room for this.$"
