SevenIsland_PokemonCenter_1F_Text_EventsDependingOnConnections::
    .string "On this island, different events\n"
    .string "occur depending on connections.\p"
    .string "What are those connections?\p"
    .string "They are for you to discover on\n"
    .string "your own.$"

SevenIsland_PokemonCenter_1F_Text_DidYouRideSeagallopHere::
    .string "Did you ride a SEAGALLOP ferry\n"
    .string "to get here?\p"
    .string "There are at least ten of those\n"
    .string "high-speed ships.\p"
    .string "I don't know where they all go,\n"
    .string "though.$"

SevenIsland_PokemonCenter_1F_Text_CheckOutTrainerTower::
    .string "If you're confident, you should\n"
    .string "check out TRAINER TOWER.$"

SevenIsland_PokemonCenter_1F_Text_DoYouHaveMonWantToTradeForMyMon::
	.string "Hi!\n"
	.string "Do you have a {STR_VAR_1}?\p"
	.string "Want to trade it for my\n"
	.string "{STR_VAR_2}?$"

SevenIsland_PokemonCenter_1F_Text_ThatsTooBad::
	.string "That's too bad.$"

SevenIsland_PokemonCenter_1F_Text_ThisIsNoMon::
	.string "…This is no {STR_VAR_1}.\p"
	.string "If you get one, please trade it\n"
	.string "to me!$"

SevenIsland_PokemonCenter_1F_Text_ThankYou::
	.string "Thank you!$"

SevenIsland_PokemonCenter_1F_Text_HowIsMyOldMon::
	.string "How is my old {STR_VAR_2}?\p"
	.string "My {STR_VAR_1} is doing great!$"
