Route13_MoveRelearnerHouse_Text_TeachWhichMove::
# 1 "data/maps/Route13_MoveRelearnerHouse/text.pory"
	.string "Which move should I teach?$"

Route13_MoveRelearnerHouse_Text_NoMoveICanTeachThatMon::
# 5 "data/maps/Route13_MoveRelearnerHouse/text.pory"
	.string "Sorry…\p"
	.string "It doesn't appear as if I have a\n"
	.string "move I can teach that POKéMON.$"

Route13_MoveRelearnerHouse_Text_CantTeachAnEgg::
# 11 "data/maps/Route13_MoveRelearnerHouse/text.pory"
	.string "Hmm? There isn't a single move\n"
	.string "that I can teach an EGG.$"

Route13_MoveRelearnerHouse_Text_EndTutorMove::
# 16 "data/maps/Route13_MoveRelearnerHouse/text.pory"
	.string "Come back if you find some STARDUST\n"
	.string "and want your POKéMON to remember\l"
	.string "a move from its past.$"
