SixIsland_PokemonCenter_1F_Text_SomethingHiddenOnThisIsland::
    .string "For ten years, I've searched for\n"
    .string "RUINS.\p"
    .string "No, make that twenty years.\p"
    .string "I get this feeling that there's\n"
    .string "something hidden on this island.$"

SixIsland_PokemonCenter_1F_Text_SomeMonsEvolveByTradingWithHeldItem::
    .string "You know of POKéMON that evolved\n"
    .string "only upon trading, yes?\p"
    .string "But did you know that there are\n"
    .string "still others?\p"
    .string "Some POKéMON evolve only when\n"
    .string "given holding specific items.$"

SixIsland_PokemonCenter_1F_Text_RivalImpossibleToGetAllMonsAroundHere::
    .string "{RIVAL}: Hey, {PLAYER}!\n"
    .string "How's your POKéDEX filling up?\p"
    .string "It looks like it's impossible to get\n"
    .string "all the POKéMON by hanging around\l"
    .string "just these parts.\p"
    .string "Maybe there are POKéMON we don't\n"
    .string "know about somewhere far away…\p"
    .string "… … …  … … …  … … …\p"
    .string "Well, if I can't do it, there's no\n"
    .string "way for you to get it done.\p"
    .string "I'm not going to get all desperate\n"
    .string "over this.\p"
    .string "I'll keep collecting POKéMON at my\n"
    .string "own pace while I train them.\p"
    .string "That's what I'll do.\n"
    .string "So there's no point staying here.\l"
    .string "I may as well leave for home.\p"
    .string "That's that, then!\n"
    .string "Smell ya later!$"

SixIsland_PokemonCenter_1F_Text_DoYouHaveMonWantToTradeForMyMon::
	.string "Hi!\n"
	.string "Do you have a {STR_VAR_1}?\p"
	.string "Want to trade it for my\n"
	.string "{STR_VAR_2}?$"

SixIsland_PokemonCenter_1F_Text_ThatsTooBad::
	.string "That's too bad.$"

SixIsland_PokemonCenter_1F_Text_ThisIsNoMon::
	.string "…This is no {STR_VAR_1}.\p"
	.string "If you get one, please trade it\n"
	.string "to me!$"

SixIsland_PokemonCenter_1F_Text_ThankYou::
	.string "Thank you!$"

SixIsland_PokemonCenter_1F_Text_HowIsMyOldMon::
	.string "How is my old {STR_VAR_2}?\p"
	.string "My {STR_VAR_1} is doing great!$"
