FiveIsland_PokemonCenter_1F_Text_OnMyWayToPrepareMeal::
    .string "I'm on my way to prepare a meal\n"
    .string "for a certain high-society person.$"

FiveIsland_PokemonCenter_1F_Text_YoureOnQuestToCatchEveryMon::
    .string "You're on a quest to catch every\n"
    .string "single kind of POKéMON?\p"
    .string "…How incredible. Please tell me if\n"
    .string "you catch a strong one!$"

FiveIsland_PokemonCenter_1F_Text_DoYouHaveMonWantToTradeForMyMon::
	.string "Hi!\n"
	.string "Do you have a {STR_VAR_1}?\p"
	.string "Want to trade it for my\n"
	.string "{STR_VAR_2}?$"

FiveIsland_PokemonCenter_1F_Text_ThatsTooBad::
	.string "That's too bad.$"

FiveIsland_PokemonCenter_1F_Text_ThisIsNoMon::
	.string "…This is no {STR_VAR_1}.\p"
	.string "If you get one, please trade it\n"
	.string "to me!$"

FiveIsland_PokemonCenter_1F_Text_ThankYou::
	.string "Thank you!$"

FiveIsland_PokemonCenter_1F_Text_HowIsMyOldMon::
	.string "How is my old {STR_VAR_2}?\p"
	.string "My {STR_VAR_1} is doing great!$"

