FourIsland_IcefallCave_Entrance_Text_DoYouHaveMonWantToTradeForMyMon::
	.string "Hi!\n"
	.string "Do you have a {STR_VAR_1}?\p"
	.string "Want to trade it for my\n"
	.string "{STR_VAR_2}?$"

FourIsland_IcefallCave_Entrance_Text_ThatsTooBad::
	.string "That's too bad.$"

FourIsland_IcefallCave_Entrance_Text_ThisIsNoMon::
	.string "…This is no {STR_VAR_1}.\p"
	.string "If you get one, please trade it\n"
	.string "to me!$"

FourIsland_IcefallCave_Entrance_Text_ThankYou::
	.string "Thank you!$"

FourIsland_IcefallCave_Entrance_Text_HowIsMyOldMon::
	.string "How is my old {STR_VAR_2}?\p"
	.string "My {STR_VAR_1} is doing great!$"
